package co.ec.cnsyn.codecatcher.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF003A6A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF265D98)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF4E5F78)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD6E5FF)
val onSecondaryContainerLight = Color(0xFF394A62)
val tertiaryLight = Color(0xFF494C51)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF6D7075)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF9F9FE)
val onBackgroundLight = Color(0xFF191C20)
val surfaceLight = Color(0xFFFCF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE2E2E7)
val onSurfaceVariantLight = Color(0xFF45474B)
val outlineLight = Color(0xFF75777B)
val outlineVariantLight = Color(0xFFC5C6CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFA3C9FF)
val surfaceDimLight = Color(0xFFDDD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val primaryDark = Color(0xFFA3C9FF)
val onPrimaryDark = Color(0xFF00315C)
val primaryContainerDark = Color(0xFF00437A)
val onPrimaryContainerDark = Color(0xFFC2DAFF)
val secondaryDark = Color(0xFFB6C8E4)
val onSecondaryDark = Color(0xFF203148)
val secondaryContainerDark = Color(0xFF2F4058)
val onSecondaryContainerDark = Color(0xFFC4D5F2)
val tertiaryDark = Color(0xFFC4C6CC)
val onTertiaryDark = Color(0xFF2D3135)
val tertiaryContainerDark = Color(0xFF54575C)
val onTertiaryContainerDark = Color(0xFFFDFCFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111317)
val onBackgroundDark = Color(0xFFE2E2E8)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF45474B)
val onSurfaceVariantDark = Color(0xFFC5C6CB)
val outlineDark = Color(0xFF8F9195)
val outlineVariantDark = Color(0xFF45474B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF2A609B)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353434)






